package:
  name: xwrap
  version: 0.1

source:
  git_url: https://github.com/Xett/xwrap.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  home: https://github.com/Xett/xwrap.git
